import type { Metadata } from 'next'
import { ContentShell } from '@/components/seo-page'

export const metadata: Metadata = { title: 'Frequently Asked Questions | Streamline', description: 'Answers about Streamline, live TV availability, supported countries, favorites, and public channel sources.' }

const questions = [{ question: 'Is Streamline free?', answer: 'Yes. Streamline is currently free to browse and use. Some streams may be unavailable because public sources can change or restrict access.' }, { question: 'What countries are supported?', answer: 'The directory currently has country pages for India, the United Kingdom, the United States, Canada, Australia, and Germany, with more countries planned as the library grows.' }, { question: 'How do favorites work?', answer: 'From the Streamline app, select the heart beside a channel to add or remove it from your favorites. Favorites give you a shorter list for everyday viewing.' }, { question: 'Does Streamline host the video streams?', answer: 'No. Streamline organizes public channel sources and does not host or own the underlying broadcasts. Availability can change at any time.' }, { question: 'Why is a channel unavailable?', answer: 'A source may be offline, testing, geo-restricted, or temporarily changed by its provider. Try another channel or return later.' }, { question: 'Can I suggest a channel?', answer: 'Yes. Send a suggestion through the contact page with the channel name, country, and a public source if you have one.' }]

export default function FAQPage() {
  return <ContentShell><main className="mx-auto max-w-4xl px-6 py-16 lg:px-10 lg:py-24"><p className="text-xs font-semibold uppercase tracking-[0.22em] text-teal-300">Help center</p><h1 className="mt-4 text-4xl font-semibold tracking-tight sm:text-6xl">Frequently asked questions</h1><div className="mt-14 divide-y divide-zinc-800 border-y border-zinc-800">{questions.map((item) => <details key={item.question} className="group py-6"><summary className="cursor-pointer list-none pr-8 text-lg font-medium text-zinc-100 marker:hidden">{item.question}<span className="float-right text-teal-300 transition group-open:rotate-45">+</span></summary><p className="mt-4 max-w-2xl text-base leading-8 text-zinc-400">{item.answer}</p></details>)}</div></main></ContentShell>
}
